### ISSUE TITLE
PiggyCE being removed and Keys becoming non keys

### ISSUE THREAD

**Issue by BroCrows** [nikoskon2003/ChestVault#2]
So I downloaded this plugin and once my players started realizing it was on the server they instantly found a bug with ce. The first incident was with radar enchant and it was removed when he put it in the chest. Also another bug was with keys they keep becoming non-keys when I put them in VaultChest.

**Comment by nikoskon2003** [comment]
Issues fixed

**Comment by BroCrows** [comment]
Thx
